---
- name: Install Java and net-tools
  hosts: aws
  become: yes
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install java version
      apt:
        name: openjdk-8-jdk
    - name: Install net-tools
      apt:
        name: net-tools
- name: Download and unpack nexus installer
  hosts: aws
  become: yes
  tasks:
    - name: Download nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.57.0-01-unix.tar.gz
        dest: /opt
      register: download_result
    - debug:
        msg: "{{ download_result }}"
    - name: Check if nexus folder exists
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Untar nexus installer
      unarchive:
        # src: /opt/nexus-3.57.0-01-unix.tar.gz
        src: "{{ download_result.dest }}"
        remote_src: yes
        dest: /opt/
      when: not stat_result.stat.exists
    - name: Find the nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - debug:
        msg: "{{ find_result }}"
    - debug:
        msg: "{{ stat_result.stat.exists }}"
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Create Nexus user to own nexus folder
  hosts: aws
  become: yes
  tasks:
    - name: Ensure group nexus exists
      group:
        name: nexus
        state: present
    - name: Create nexus
      user:
        name: nexus
        group: nexus
    - name: make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
- name: Start nexus with nexus user
  hosts: aws
  become: yes
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
      blockinfile:
        path: /opt/nexus/bin/nexus.rc
        block: |
          run_as_user="nexus"
    - name: Start the nexus
      command: /opt/nexus/bin/nexus start

- name: Verify nexus running
  hosts: aws
  become: yes
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}
    - name: check the netstat
      shell: netstat -lnpt
      register: netstat_status
    - debug: msg={{ netstat_status.stdout_lines}}
