---
- name: Install node and npm
  hosts: aws
  become: yes
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create a new linux user
  hosts: aws
  become: yes
  vars_files:
    - project-vars
  tasks:
    - name: Create linux user
      user:
        name: "{{ new_user }}"
        comment: Ibrar admin
        group: sudo

- name: Deploying nodejs app
  hosts: aws
  become: True
  become_user: "{{ new_user }}"
  vars_files:
    - project-vars
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: /mnt/c/ansible-project-learning/nodejs-app/nodejs-app-1.0.0.tgz
        dest: "{{ user_home_directory_path }}nodejs-app-1.0.0.tgz"
    - name: Unpack the nodejs file
      unarchive:
        src: /home/ibrar/nodejs-app-1.0.0.tgz
        remote_src: yes
        dest: /home/ibrar/
    - name: install the dependencies
      npm:
        path: /home/ibrar/package
    - name: Start the Application
      command:
        chdir: /home/ibrar/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}
